# Generated by Django 4.0.3 on 2022-03-30 22:18

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/DELL/Desktop/ONLINE TICKET BOOKING SYSTEM/myapp/public/images/games'))),
            ],
        ),
    ]
