# Generated by Django 4.0.3 on 2022-03-30 22:50

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team1_name', models.CharField(max_length=50)),
                ('team2_name', models.CharField(max_length=50)),
                ('team1_image', models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/DELL/Desktop/ONLINE TICKET BOOKING SYSTEM/myapp/public/images/teams'))),
                ('team2_image', models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/DELL/Desktop/ONLINE TICKET BOOKING SYSTEM/myapp/public/images/teams'))),
                ('start_time', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.game')),
            ],
        ),
    ]
